const unidadesSAT = [
  { label: "Pieza - Múltiplos / Fracciones / Decimales (H87)", value: "H87" },
  { label: "Elemento - Unidades de venta (EA)", value: "EA" },
  { label: "Unidad de Servicio - Unidades específicas de la industria (E48)", value: "E48" },
  { label: "Actividad - Unidades de venta (ACT)", value: "ACT" },
  { label: "Kilogramo - Mecánica (KGM)", value: "KGM" },
  { label: "Trabajo - Unidades específicas de la industria (E51)", value: "E51" },
  { label: "Tarifa - Diversos (A9)", value: "A9" },
  { label: "Metro - Tiempo y Espacio (MTR)", value: "MTR" },
  { label: "Paquete a granel - Diversos (AB)", value: "AB" },
  { label: "Caja base - Unidades específicas de la industria (BB)", value: "BB" },
  { label: "Kit - Unidades de venta (KT)", value: "KT" },
  { label: "Conjunto - Unidades de venta (SET)", value: "SET" },
  { label: "Litro - Tiempo y Espacio (LTR)", value: "LTR" },
  { label: "Caja - Unidades de empaque (XBX)", value: "XBX" },
  { label: "Mes - Tiempo y Espacio (MON)", value: "MON" },
  { label: "Hora - Tiempo y Espacio (HUR)", value: "HUR" },
  { label: "Metro cuadrado - Tiempo y Espacio (MTK)", value: "MTK" },
  { label: "Equipos - Diversos (11)", value: "11" },
  { label: "Miligramo - Mecánica (MGM)", value: "MGM" },
  { label: "Paquete - Unidades de empaque (XPK)", value: "XPK" },
  { label: "Kit (Conjunto de piezas) - Unidades de empaque (XKI)", value: "XKI" },
  { label: "Variedad - Diversos (AS)", value: "AS" },
  { label: "Gramo - Mecánica (GRM)", value: "GRM" },
  { label: "Par - Números enteros / Números / Ratios (PR)", value: "PR" },
  { label: "Docenas de piezas - Unidades de venta (DPC)", value: "DPC" },
  { label: "Unidad - Unidades de empaque (xun)", value: "xun" },
  { label: "Día - Tiempo y Espacio (DAY)", value: "DAY" },
  { label: "Lote - Unidades de empaque (XLT)", value: "XLT" },
  { label: "Grupos - Diversos (10)", value: "10" },
  { label: "Mililitro - Tiempo y Espacio (MLT)", value: "MLT" },
  { label: "Viaje - Unidades específicas de la industria (E54)", value: "E54" }
];

export default unidadesSAT;
